---
- hosts: forti
  gather_facts: no
  connection: local

  tasks:
    - name: Backup current config
      fortios_config:
        host: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        backup_path: /Users/Desktop/tmp/ForiGate/  # バックアップ先ディレクトリ
        backup_filename: test.config
        backup: yes  # バックアップする指定